[package]
name = "purple-sys"
version = "0.1.0"
authors = ["Jack Coulter <jscinoz@jscinoz.so>"]
keywords = ["pidgin", "purple", "libpurple"]
build = "build.rs"
links = "purple"

[build-dependencies]
pkg-config = "*"
libc = "*"
bindgen = "*"
